development:
  adapter: postgresql
  encoding: unicode
  database: marketplace_development
  pool: 5
  username: marketplace
  password: marketplace

test:
  adapter: postgresql
  encoding: unicode
  database: marketplace_test
  pool: 5
  username: marketplace
  password: marketplace
